### ISSUE TITLE
Bulldozing paths that are underconstruction give limited money

### ISSUE THREAD

**Issue by J-Pinelli** [swe-teamteam/OpenRCT2#1]
**OS:** [Windows 10]
**Version:** [?]
**Commit/Build:** [?]

Provides unlimited money if you hold down bulldozer on a uncompleted path.

- [ X] Reproducible in RCT2 (vanilla)?
- [X ] Multiplayer?

**Steps to reproduce:**
1. Open build path and click on continuous path (right button of the two at the bottom of path window)
2. Build a small patch
3. Click on bulldozer in the upper right hand corner, and click on Footpath box in the window that appears.
4. Click and hold on path that is not yet completed.
5. $$$$$$$$$$$$$$$$$

**Comment by crorabaugh2015** [comment]
error is in src/openrct2//world/footpath.c on lines 412-453 (most likely) - J-Pinelli discovered this

**Comment by crorabaugh2015** [comment]
fixed:
https://github.com/swe-teamteam/OpenRCT2/commit/97b7c98f1e24f257a3dffc0830fde41c9b78fa69
