### ISSUE TITLE
Wrong Name on a Ride

### ISSUE THREAD

**Issue by brocco1i** [swe-teamteam/OpenRCT2#2]
OS: Windows 10
Version: 
Commit/Build: 

When building a Giga Coaster, the name of a prebuilt coaster is displayed as "Goliath.1" instead of as "Goliath". 

Reproducable

Steps to reproduce:

Open a park with the Giga Coaster available (I Used North America in Wacky Worlds)
Build a new Giga Coaster

Screenshots / Video:

![goliath bug](https://cloud.githubusercontent.com/assets/25679260/24177493/479f21be-0e79-11e7-95b6-94a3e5da435c.PNG)

**Comment by brocco1i** [comment]
Name should be "Goliath" and not "Goliath.1"

**Comment by crorabaugh2015** [comment]
As explained in the issue on the official page ([https://github.com/OpenRCT2/OpenRCT2/issues/5077]), there are two Goliath files in OpenRCT2, Goliath.TD6 and Goliath.1.TD6. These are in the original RCT2 install
