### ISSUE TITLE
Segfault at end of intro

### ISSUE THREAD

**Issue by crorabaugh2015** [swe-teamteam/OpenRCT2#6]
**OS:** Ubuntu 16.04
**Version:** 
**Commit/Build:** [e.g. 426e106]

When intro is turned on (change in config.ini, located where the game saves files), game crashes at the end of the intro.

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Change intro to true in config.ini
2. Open game, it should crash at end of intro

**Dump file**

**Screenshots / Video:**

**Save game:**

**Comment by J-Pinelli** [comment]
Dosent seem to be replicate in the Windows Version. Others comments on the main page indicate its Linux/Mac only

**Comment by crorabaugh2015** [comment]
original issue: https://github.com/OpenRCT2/OpenRCT2/issues/5288
